/* eslint-disable */
// allocate.guarded.ts — GENERATED by `lemmascript-guard`. Do not edit.
// Drop-in for allocate.ts: each function checks its //@ requires and throws
// PreconditionError on violation; `can.*` runs the same checks as booleans.

import * as __core from "./allocate.js";

export class PreconditionError extends Error {
  readonly fn: string;
  readonly clause: string;
  readonly clauseId: string;
  readonly args: unknown[];
  readonly detail: unknown;
  constructor(fn: string, clause: string, clauseId: string, args: unknown[], detail: unknown) {
    super(`precondition failed in ${fn}: ${clause}`);
    this.name = "PreconditionError";
    this.fn = fn; this.clause = clause; this.clauseId = clauseId; this.args = args; this.detail = detail;
    Object.defineProperty(this, "args", { enumerable: false });
    Object.defineProperty(this, "detail", { enumerable: false });
  }
}

type __Check = { id: string; clause: string; ok: boolean; detail: () => unknown };
const __C = (id: string, clause: string, ok: boolean, detail: () => unknown): __Check => ({ id, clause, ok, detail });
function __enforce<R>(fn: string, args: unknown[], checks: __Check[], call: () => R): R {
  for (const c of checks) if (!c.ok) throw new PreconditionError(fn, c.clause, c.id, args, c.detail());
  return call();
}
const __holds = (checks: __Check[]): boolean => checks.every((c) => c.ok);

type __P_sumTo = Parameters<typeof __core.sumTo>;
function checks_sumTo(arr: __P_sumTo[0], n: __P_sumTo[1]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = (((0 <= n) && (n <= arr.length)));
  __cs.push(__C("sumTo#0", "0 <= n && n <= arr.length", __ok0, () => ({ "n": n, "arr.length": arr.length })));
  if (!__ok0) return __cs;
  return __cs;
}
export function sumTo(...args: __P_sumTo): ReturnType<typeof __core.sumTo> {
  return __enforce("sumTo", args, checks_sumTo(...args), () => __core.sumTo(...args));
}
type __P_allocate = Parameters<typeof __core.allocate>;
function checks_allocate(total: __P_allocate[0], weights: __P_allocate[1], G: __P_allocate[2]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((total >= 0));
  __cs.push(__C("allocate#0", "total >= 0", __ok0, () => ({ "total": total })));
  if (!__ok0) return __cs;
  const __ok1 = ((weights.length >= 1));
  __cs.push(__C("allocate#1", "weights.length >= 1", __ok1, () => ({ "weights.length": weights.length })));
  if (!__ok1) return __cs;
  const __w2 = ((): number | undefined => { for (let k = 0; k < weights.length; k++) { if (!((!(((0 <= k) && (k < weights.length))) || ((weights[k] >= 0))))) return k; } return undefined; })();
  const __ok2 = (__w2 === undefined);
  __cs.push(__C("allocate#2", "forall(k, 0 <= k && k < weights.length ==> weights[k] >= 0)", __ok2, () => ({ "k": __w2 })));
  if (!__ok2) return __cs;
  const __ok3 = ((__core.sumTo(weights, weights.length) >= 1));
  __cs.push(__C("allocate#3", "sumTo(weights, weights.length) >= 1", __ok3, () => ({ "sumTo(weights, weights.length)": __core.sumTo(weights, weights.length) })));
  if (!__ok3) return __cs;
  const __ok4 = ((G >= 1));
  __cs.push(__C("allocate#4", "G >= 1", __ok4, () => ({ "G": G })));
  if (!__ok4) return __cs;
  return __cs;
}
export function allocate(...args: __P_allocate): ReturnType<typeof __core.allocate> {
  return __enforce("allocate", args, checks_allocate(...args), () => __core.allocate(...args));
}
type __P_billTotals = Parameters<typeof __core.billTotals>;
function checks_billTotals(subtotals: __P_billTotals[0], tax: __P_billTotals[1], tip: __P_billTotals[2], G: __P_billTotals[3]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((subtotals.length >= 1));
  __cs.push(__C("billTotals#0", "subtotals.length >= 1", __ok0, () => ({ "subtotals.length": subtotals.length })));
  if (!__ok0) return __cs;
  const __w1 = ((): number | undefined => { for (let k = 0; k < subtotals.length; k++) { if (!((!(((0 <= k) && (k < subtotals.length))) || ((subtotals[k] >= 0))))) return k; } return undefined; })();
  const __ok1 = (__w1 === undefined);
  __cs.push(__C("billTotals#1", "forall(k, 0 <= k && k < subtotals.length ==> subtotals[k] >= 0)", __ok1, () => ({ "k": __w1 })));
  if (!__ok1) return __cs;
  const __ok2 = ((__core.sumTo(subtotals, subtotals.length) >= 1));
  __cs.push(__C("billTotals#2", "sumTo(subtotals, subtotals.length) >= 1", __ok2, () => ({ "sumTo(subtotals, subtotals.length)": __core.sumTo(subtotals, subtotals.length) })));
  if (!__ok2) return __cs;
  const __ok3 = ((tax >= 0));
  __cs.push(__C("billTotals#3", "tax >= 0", __ok3, () => ({ "tax": tax })));
  if (!__ok3) return __cs;
  const __ok4 = ((tip >= 0));
  __cs.push(__C("billTotals#4", "tip >= 0", __ok4, () => ({ "tip": tip })));
  if (!__ok4) return __cs;
  const __ok5 = ((G >= 1));
  __cs.push(__C("billTotals#5", "G >= 1", __ok5, () => ({ "G": G })));
  if (!__ok5) return __cs;
  return __cs;
}
export function billTotals(...args: __P_billTotals): ReturnType<typeof __core.billTotals> {
  return __enforce("billTotals", args, checks_billTotals(...args), () => __core.billTotals(...args));
}
type __P_itemShare = Parameters<typeof __core.itemShare>;
function checks_itemShare(price: __P_itemShare[0], claimers: __P_itemShare[1], claimerWeights: __P_itemShare[2], n: __P_itemShare[3], G: __P_itemShare[4]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((price >= 0));
  __cs.push(__C("itemShare#0", "price >= 0", __ok0, () => ({ "price": price })));
  if (!__ok0) return __cs;
  const __ok1 = ((n >= 1));
  __cs.push(__C("itemShare#1", "n >= 1", __ok1, () => ({ "n": n })));
  if (!__ok1) return __cs;
  const __ok2 = ((claimers.length >= 1));
  __cs.push(__C("itemShare#2", "claimers.length >= 1", __ok2, () => ({ "claimers.length": claimers.length })));
  if (!__ok2) return __cs;
  const __ok3 = ((claimers.length === claimerWeights.length));
  __cs.push(__C("itemShare#3", "claimers.length === claimerWeights.length", __ok3, () => ({ "claimers.length": claimers.length, "claimerWeights.length": claimerWeights.length })));
  if (!__ok3) return __cs;
  const __w4 = ((): number | undefined => { for (let j = 0; j < claimers.length; j++) { if (!((!(((0 <= j) && (j < claimers.length))) || (((0 <= claimers[j]) && (claimers[j] < n)))))) return j; } return undefined; })();
  const __ok4 = (__w4 === undefined);
  __cs.push(__C("itemShare#4", "forall(j, 0 <= j && j < claimers.length ==> 0 <= claimers[j] && claimers[j] < n)", __ok4, () => ({ "j": __w4 })));
  if (!__ok4) return __cs;
  const __w5 = ((): number | undefined => { for (let j = 0; j < claimerWeights.length; j++) { if (!((!(((0 <= j) && (j < claimerWeights.length))) || ((claimerWeights[j] >= 0))))) return j; } return undefined; })();
  const __ok5 = (__w5 === undefined);
  __cs.push(__C("itemShare#5", "forall(j, 0 <= j && j < claimerWeights.length ==> claimerWeights[j] >= 0)", __ok5, () => ({ "j": __w5 })));
  if (!__ok5) return __cs;
  const __ok6 = ((__core.sumTo(claimerWeights, claimerWeights.length) >= 1));
  __cs.push(__C("itemShare#6", "sumTo(claimerWeights, claimerWeights.length) >= 1", __ok6, () => ({ "sumTo(claimerWeights, claimerWeights.length)": __core.sumTo(claimerWeights, claimerWeights.length) })));
  if (!__ok6) return __cs;
  const __ok7 = ((G >= 1));
  __cs.push(__C("itemShare#7", "G >= 1", __ok7, () => ({ "G": G })));
  if (!__ok7) return __cs;
  return __cs;
}
export function itemShare(...args: __P_itemShare): ReturnType<typeof __core.itemShare> {
  return __enforce("itemShare", args, checks_itemShare(...args), () => __core.itemShare(...args));
}
type __P_vectorAdd = Parameters<typeof __core.vectorAdd>;
function checks_vectorAdd(a: __P_vectorAdd[0], b: __P_vectorAdd[1]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((a.length === b.length));
  __cs.push(__C("vectorAdd#0", "a.length === b.length", __ok0, () => ({ "a.length": a.length, "b.length": b.length })));
  if (!__ok0) return __cs;
  return __cs;
}
export function vectorAdd(...args: __P_vectorAdd): ReturnType<typeof __core.vectorAdd> {
  return __enforce("vectorAdd", args, checks_vectorAdd(...args), () => __core.vectorAdd(...args));
}
type __P_itemSubtotals = Parameters<typeof __core.itemSubtotals>;
function checks_itemSubtotals(itemVectors: __P_itemSubtotals[0], prices: __P_itemSubtotals[1], n: __P_itemSubtotals[2]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((n >= 1));
  __cs.push(__C("itemSubtotals#0", "n >= 1", __ok0, () => ({ "n": n })));
  if (!__ok0) return __cs;
  const __ok1 = ((itemVectors.length === prices.length));
  __cs.push(__C("itemSubtotals#1", "itemVectors.length === prices.length", __ok1, () => ({ "itemVectors.length": itemVectors.length, "prices.length": prices.length })));
  if (!__ok1) return __cs;
  const __w2 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { const __e0 = itemVectors[i]; if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__e0.length === n))))) return i; } return undefined; })();
  const __ok2 = (__w2 === undefined);
  __cs.push(__C("itemSubtotals#2", "forall(i, 0 <= i && i < itemVectors.length ==> itemVectors[i].length === n)", __ok2, () => ({ "i": __w2 })));
  if (!__ok2) return __cs;
  const __w3 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__core.sumTo(itemVectors[i], n) === prices[i]))))) return i; } return undefined; })();
  const __ok3 = (__w3 === undefined);
  __cs.push(__C("itemSubtotals#3", "forall(i, 0 <= i && i < itemVectors.length ==> sumTo(itemVectors[i], n) === prices[i])", __ok3, () => ({ "i": __w3 })));
  if (!__ok3) return __cs;
  const __w4 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((() => { for (let k = 0; k < n; k++) { if (!((!(((0 <= k) && (k < n))) || ((itemVectors[i][k] >= 0))))) return false; } return true; })())))) return i; } return undefined; })();
  const __ok4 = (__w4 === undefined);
  __cs.push(__C("itemSubtotals#4", "forall(i, 0 <= i && i < itemVectors.length ==> forall(k, 0 <= k && k < n ==> itemVectors[i][k] >= 0))", __ok4, () => ({ "i": __w4 })));
  if (!__ok4) return __cs;
  return __cs;
}
export function itemSubtotals(...args: __P_itemSubtotals): ReturnType<typeof __core.itemSubtotals> {
  return __enforce("itemSubtotals", args, checks_itemSubtotals(...args), () => __core.itemSubtotals(...args));
}
type __P_bill = Parameters<typeof __core.bill>;
function checks_bill(itemVectors: __P_bill[0], prices: __P_bill[1], tax: __P_bill[2], tip: __P_bill[3], n: __P_bill[4], G: __P_bill[5]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((n >= 1));
  __cs.push(__C("bill#0", "n >= 1", __ok0, () => ({ "n": n })));
  if (!__ok0) return __cs;
  const __ok1 = ((itemVectors.length === prices.length));
  __cs.push(__C("bill#1", "itemVectors.length === prices.length", __ok1, () => ({ "itemVectors.length": itemVectors.length, "prices.length": prices.length })));
  if (!__ok1) return __cs;
  const __w2 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { const __e0 = itemVectors[i]; if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__e0.length === n))))) return i; } return undefined; })();
  const __ok2 = (__w2 === undefined);
  __cs.push(__C("bill#2", "forall(i, 0 <= i && i < itemVectors.length ==> itemVectors[i].length === n)", __ok2, () => ({ "i": __w2 })));
  if (!__ok2) return __cs;
  const __w3 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__core.sumTo(itemVectors[i], n) === prices[i]))))) return i; } return undefined; })();
  const __ok3 = (__w3 === undefined);
  __cs.push(__C("bill#3", "forall(i, 0 <= i && i < itemVectors.length ==> sumTo(itemVectors[i], n) === prices[i])", __ok3, () => ({ "i": __w3 })));
  if (!__ok3) return __cs;
  const __w4 = ((): number | undefined => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((() => { for (let k = 0; k < n; k++) { if (!((!(((0 <= k) && (k < n))) || ((itemVectors[i][k] >= 0))))) return false; } return true; })())))) return i; } return undefined; })();
  const __ok4 = (__w4 === undefined);
  __cs.push(__C("bill#4", "forall(i, 0 <= i && i < itemVectors.length ==> forall(k, 0 <= k && k < n ==> itemVectors[i][k] >= 0))", __ok4, () => ({ "i": __w4 })));
  if (!__ok4) return __cs;
  const __ok5 = ((__core.sumTo(prices, prices.length) >= 1));
  __cs.push(__C("bill#5", "sumTo(prices, prices.length) >= 1", __ok5, () => ({ "sumTo(prices, prices.length)": __core.sumTo(prices, prices.length) })));
  if (!__ok5) return __cs;
  const __ok6 = ((tax >= 0));
  __cs.push(__C("bill#6", "tax >= 0", __ok6, () => ({ "tax": tax })));
  if (!__ok6) return __cs;
  const __ok7 = ((tip >= 0));
  __cs.push(__C("bill#7", "tip >= 0", __ok7, () => ({ "tip": tip })));
  if (!__ok7) return __cs;
  const __ok8 = ((G >= 1));
  __cs.push(__C("bill#8", "G >= 1", __ok8, () => ({ "G": G })));
  if (!__ok8) return __cs;
  return __cs;
}
export function bill(...args: __P_bill): ReturnType<typeof __core.bill> {
  return __enforce("bill", args, checks_bill(...args), () => __core.bill(...args));
}
type __P_balances = Parameters<typeof __core.balances>;
function checks_balances(paid: __P_balances[0], owed: __P_balances[1]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((paid.length === owed.length));
  __cs.push(__C("balances#0", "paid.length === owed.length", __ok0, () => ({ "paid.length": paid.length, "owed.length": owed.length })));
  if (!__ok0) return __cs;
  const __ok1 = ((__core.sumTo(paid, paid.length) === __core.sumTo(owed, owed.length)));
  __cs.push(__C("balances#1", "sumTo(paid, paid.length) === sumTo(owed, owed.length)", __ok1, () => ({ "sumTo(paid, paid.length)": __core.sumTo(paid, paid.length), "sumTo(owed, owed.length)": __core.sumTo(owed, owed.length) })));
  if (!__ok1) return __cs;
  return __cs;
}
export function balances(...args: __P_balances): ReturnType<typeof __core.balances> {
  return __enforce("balances", args, checks_balances(...args), () => __core.balances(...args));
}
type __P_settle = Parameters<typeof __core.settle>;
function checks_settle(balances: __P_settle[0]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((balances.length >= 1));
  __cs.push(__C("settle#0", "balances.length >= 1", __ok0, () => ({ "balances.length": balances.length })));
  if (!__ok0) return __cs;
  const __ok1 = ((__core.sumTo(balances, balances.length) === 0));
  __cs.push(__C("settle#1", "sumTo(balances, balances.length) === 0", __ok1, () => ({ "sumTo(balances, balances.length)": __core.sumTo(balances, balances.length) })));
  if (!__ok1) return __cs;
  return __cs;
}
export function settle(...args: __P_settle): ReturnType<typeof __core.settle> {
  return __enforce("settle", args, checks_settle(...args), () => __core.settle(...args));
}
type __P_roundToG = Parameters<typeof __core.roundToG>;
function checks_roundToG(_x: __P_roundToG[0], G: __P_roundToG[1]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((G >= 1));
  __cs.push(__C("roundToG#0", "G >= 1", __ok0, () => ({ "G": G })));
  if (!__ok0) return __cs;
  return __cs;
}
export function roundToG(...args: __P_roundToG): ReturnType<typeof __core.roundToG> {
  return __enforce("roundToG", args, checks_roundToG(...args), () => __core.roundToG(...args));
}
type __P_settleRounded = Parameters<typeof __core.settleRounded>;
function checks_settleRounded(balances: __P_settleRounded[0], hub: __P_settleRounded[1], G: __P_settleRounded[2]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((balances.length >= 1));
  __cs.push(__C("settleRounded#0", "balances.length >= 1", __ok0, () => ({ "balances.length": balances.length })));
  if (!__ok0) return __cs;
  const __ok1 = (((0 <= hub) && (hub < balances.length)));
  __cs.push(__C("settleRounded#1", "0 <= hub && hub < balances.length", __ok1, () => ({ "hub": hub, "balances.length": balances.length })));
  if (!__ok1) return __cs;
  const __ok2 = ((G >= 1));
  __cs.push(__C("settleRounded#2", "G >= 1", __ok2, () => ({ "G": G })));
  if (!__ok2) return __cs;
  return __cs;
}
export function settleRounded(...args: __P_settleRounded): ReturnType<typeof __core.settleRounded> {
  return __enforce("settleRounded", args, checks_settleRounded(...args), () => __core.settleRounded(...args));
}
type __P_applyOp = Parameters<typeof __core.applyOp>;
function checks_applyOp(bal: __P_applyOp[0], from: __P_applyOp[1], to: __P_applyOp[2], _amount: __P_applyOp[3]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = (((0 <= from) && (from < bal.length)));
  __cs.push(__C("applyOp#0", "0 <= from && from < bal.length", __ok0, () => ({ "from": from, "bal.length": bal.length })));
  if (!__ok0) return __cs;
  const __ok1 = (((0 <= to) && (to < bal.length)));
  __cs.push(__C("applyOp#1", "0 <= to && to < bal.length", __ok1, () => ({ "to": to, "bal.length": bal.length })));
  if (!__ok1) return __cs;
  return __cs;
}
export function applyOp(...args: __P_applyOp): ReturnType<typeof __core.applyOp> {
  return __enforce("applyOp", args, checks_applyOp(...args), () => __core.applyOp(...args));
}
type __P_replay = Parameters<typeof __core.replay>;
function checks_replay(froms: __P_replay[0], tos: __P_replay[1], amounts: __P_replay[2], n: __P_replay[3]): __Check[] {
  const __cs: __Check[] = [];
  const __ok0 = ((n >= 1));
  __cs.push(__C("replay#0", "n >= 1", __ok0, () => ({ "n": n })));
  if (!__ok0) return __cs;
  const __ok1 = ((froms.length === tos.length));
  __cs.push(__C("replay#1", "froms.length === tos.length", __ok1, () => ({ "froms.length": froms.length, "tos.length": tos.length })));
  if (!__ok1) return __cs;
  const __ok2 = ((tos.length === amounts.length));
  __cs.push(__C("replay#2", "tos.length === amounts.length", __ok2, () => ({ "tos.length": tos.length, "amounts.length": amounts.length })));
  if (!__ok2) return __cs;
  const __w3 = ((): number | undefined => { for (let k = 0; k < froms.length; k++) { if (!((!(((0 <= k) && (k < froms.length))) || (((0 <= froms[k]) && (froms[k] < n)))))) return k; } return undefined; })();
  const __ok3 = (__w3 === undefined);
  __cs.push(__C("replay#3", "forall(k, 0 <= k && k < froms.length ==> 0 <= froms[k] && froms[k] < n)", __ok3, () => ({ "k": __w3 })));
  if (!__ok3) return __cs;
  const __w4 = ((): number | undefined => { for (let k = 0; k < tos.length; k++) { if (!((!(((0 <= k) && (k < tos.length))) || (((0 <= tos[k]) && (tos[k] < n)))))) return k; } return undefined; })();
  const __ok4 = (__w4 === undefined);
  __cs.push(__C("replay#4", "forall(k, 0 <= k && k < tos.length ==> 0 <= tos[k] && tos[k] < n)", __ok4, () => ({ "k": __w4 })));
  if (!__ok4) return __cs;
  return __cs;
}
export function replay(...args: __P_replay): ReturnType<typeof __core.replay> {
  return __enforce("replay", args, checks_replay(...args), () => __core.replay(...args));
}

export const can = {
  sumTo: (...args: __P_sumTo): boolean => __holds(checks_sumTo(...args)),
  allocate: (...args: __P_allocate): boolean => __holds(checks_allocate(...args)),
  billTotals: (...args: __P_billTotals): boolean => __holds(checks_billTotals(...args)),
  itemShare: (...args: __P_itemShare): boolean => __holds(checks_itemShare(...args)),
  vectorAdd: (...args: __P_vectorAdd): boolean => __holds(checks_vectorAdd(...args)),
  itemSubtotals: (...args: __P_itemSubtotals): boolean => __holds(checks_itemSubtotals(...args)),
  bill: (...args: __P_bill): boolean => __holds(checks_bill(...args)),
  balances: (...args: __P_balances): boolean => __holds(checks_balances(...args)),
  settle: (...args: __P_settle): boolean => __holds(checks_settle(...args)),
  roundToG: (...args: __P_roundToG): boolean => __holds(checks_roundToG(...args)),
  settleRounded: (...args: __P_settleRounded): boolean => __holds(checks_settleRounded(...args)),
  applyOp: (...args: __P_applyOp): boolean => __holds(checks_applyOp(...args)),
  replay: (...args: __P_replay): boolean => __holds(checks_replay(...args)),
};
