// allocate.guarded.ts — GENERATED by `lsc guard`. Do not edit.
// Drop-in for allocate.ts: each function checks its //@ requires and throws
// PreconditionError on violation; `can.*` runs the same checks as booleans.

import * as __core from "./allocate";

export class PreconditionError extends Error {
  constructor(
    readonly fn: string,
    readonly clause: string,
    readonly clauseId: string,
    readonly args: unknown[],
    readonly detail: unknown,
  ) {
    super(`precondition failed in ${fn}: ${clause}`);
    this.name = "PreconditionError";
  }
}

type __Check = { id: string; clause: string; ok: boolean; detail: () => unknown };
const __C = (id: string, clause: string, ok: boolean, detail: () => unknown): __Check => ({ id, clause, ok, detail });
function __enforce<R>(fn: string, args: unknown[], checks: __Check[], call: () => R): R {
  for (const c of checks) if (!c.ok) throw new PreconditionError(fn, c.clause, c.id, args, c.detail());
  return call();
}
const __holds = (checks: __Check[]): boolean => checks.every((c) => c.ok);

function checks_sumTo(arr: number[], n: number): __Check[] {
  return [
    __C("sumTo#0", "0 <= n && n <= arr.length", (((0 <= n) && (n <= arr.length))), () => ({ "n": n, "arr.length": arr.length })),
  ];
}
export function sumTo(arr: number[], n: number): number {
  return __enforce("sumTo", [arr, n], checks_sumTo(arr, n), () => __core.sumTo(arr, n));
}
function checks_allocate(total: number, weights: number[], G: number): __Check[] {
  const __w2 = ((): number => { for (let k = 0; k < weights.length; k++) { if (!((!(((0 <= k) && (k < weights.length))) || ((weights[k] >= 0))))) return k; } return -1; })();
  return [
    __C("allocate#0", "total >= 0", ((total >= 0)), () => ({ "total": total })),
    __C("allocate#1", "weights.length >= 1", ((weights.length >= 1)), () => ({ "weights.length": weights.length })),
    __C("allocate#2", "forall(k, 0 <= k && k < weights.length ==> weights[k] >= 0)", __w2 === -1, () => ({ "k": __w2 })),
    __C("allocate#3", "sumTo(weights, weights.length) >= 1", ((__core.sumTo(weights, weights.length) >= 1)), () => ({ "sumTo(weights, weights.length)": __core.sumTo(weights, weights.length) })),
    __C("allocate#4", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function allocate(total: number, weights: number[], G: number): number[] {
  return __enforce("allocate", [total, weights, G], checks_allocate(total, weights, G), () => __core.allocate(total, weights, G));
}
function checks_billTotals(subtotals: number[], tax: number, tip: number, G: number): __Check[] {
  const __w1 = ((): number => { for (let k = 0; k < subtotals.length; k++) { if (!((!(((0 <= k) && (k < subtotals.length))) || ((subtotals[k] >= 0))))) return k; } return -1; })();
  return [
    __C("billTotals#0", "subtotals.length >= 1", ((subtotals.length >= 1)), () => ({ "subtotals.length": subtotals.length })),
    __C("billTotals#1", "forall(k, 0 <= k && k < subtotals.length ==> subtotals[k] >= 0)", __w1 === -1, () => ({ "k": __w1 })),
    __C("billTotals#2", "sumTo(subtotals, subtotals.length) >= 1", ((__core.sumTo(subtotals, subtotals.length) >= 1)), () => ({ "sumTo(subtotals, subtotals.length)": __core.sumTo(subtotals, subtotals.length) })),
    __C("billTotals#3", "tax >= 0", ((tax >= 0)), () => ({ "tax": tax })),
    __C("billTotals#4", "tip >= 0", ((tip >= 0)), () => ({ "tip": tip })),
    __C("billTotals#5", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function billTotals(subtotals: number[], tax: number, tip: number, G: number): number[] {
  return __enforce("billTotals", [subtotals, tax, tip, G], checks_billTotals(subtotals, tax, tip, G), () => __core.billTotals(subtotals, tax, tip, G));
}
function checks_itemShare(price: number, claimers: number[], claimerWeights: number[], n: number, G: number): __Check[] {
  const __w4 = ((): number => { for (let j = 0; j < claimers.length; j++) { if (!((!(((0 <= j) && (j < claimers.length))) || (((0 <= claimers[j]) && (claimers[j] < n)))))) return j; } return -1; })();
  const __w5 = ((): number => { for (let j = 0; j < claimerWeights.length; j++) { if (!((!(((0 <= j) && (j < claimerWeights.length))) || ((claimerWeights[j] >= 0))))) return j; } return -1; })();
  return [
    __C("itemShare#0", "price >= 0", ((price >= 0)), () => ({ "price": price })),
    __C("itemShare#1", "n >= 1", ((n >= 1)), () => ({ "n": n })),
    __C("itemShare#2", "claimers.length >= 1", ((claimers.length >= 1)), () => ({ "claimers.length": claimers.length })),
    __C("itemShare#3", "claimers.length === claimerWeights.length", ((claimers.length === claimerWeights.length)), () => ({ "claimers.length": claimers.length, "claimerWeights.length": claimerWeights.length })),
    __C("itemShare#4", "forall(j, 0 <= j && j < claimers.length ==> 0 <= claimers[j] && claimers[j] < n)", __w4 === -1, () => ({ "j": __w4 })),
    __C("itemShare#5", "forall(j, 0 <= j && j < claimerWeights.length ==> claimerWeights[j] >= 0)", __w5 === -1, () => ({ "j": __w5 })),
    __C("itemShare#6", "sumTo(claimerWeights, claimerWeights.length) >= 1", ((__core.sumTo(claimerWeights, claimerWeights.length) >= 1)), () => ({ "sumTo(claimerWeights, claimerWeights.length)": __core.sumTo(claimerWeights, claimerWeights.length) })),
    __C("itemShare#7", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function itemShare(price: number, claimers: number[], claimerWeights: number[], n: number, G: number): number[] {
  return __enforce("itemShare", [price, claimers, claimerWeights, n, G], checks_itemShare(price, claimers, claimerWeights, n, G), () => __core.itemShare(price, claimers, claimerWeights, n, G));
}
function checks_vectorAdd(a: number[], b: number[]): __Check[] {
  return [
    __C("vectorAdd#0", "a.length === b.length", ((a.length === b.length)), () => ({ "a.length": a.length, "b.length": b.length })),
  ];
}
export function vectorAdd(a: number[], b: number[]): number[] {
  return __enforce("vectorAdd", [a, b], checks_vectorAdd(a, b), () => __core.vectorAdd(a, b));
}
function checks_itemSubtotals(itemVectors: number[][], prices: number[], n: number): __Check[] {
  const __w2 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((itemVectors[i].length === n))))) return i; } return -1; })();
  const __w3 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__core.sumTo(itemVectors[i], n) === prices[i]))))) return i; } return -1; })();
  const __w4 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((() => { for (let k = 0; k < n; k++) { if (!((!(((0 <= k) && (k < n))) || ((itemVectors[i][k] >= 0))))) return false; } return true; })())))) return i; } return -1; })();
  return [
    __C("itemSubtotals#0", "n >= 1", ((n >= 1)), () => ({ "n": n })),
    __C("itemSubtotals#1", "itemVectors.length === prices.length", ((itemVectors.length === prices.length)), () => ({ "itemVectors.length": itemVectors.length, "prices.length": prices.length })),
    __C("itemSubtotals#2", "forall(i, 0 <= i && i < itemVectors.length ==> itemVectors[i].length === n)", __w2 === -1, () => ({ "i": __w2 })),
    __C("itemSubtotals#3", "forall(i, 0 <= i && i < itemVectors.length ==> sumTo(itemVectors[i], n) === prices[i])", __w3 === -1, () => ({ "i": __w3 })),
    __C("itemSubtotals#4", "forall(i, 0 <= i && i < itemVectors.length ==> forall(k, 0 <= k && k < n ==> itemVectors[i][k] >= 0))", __w4 === -1, () => ({ "i": __w4 })),
  ];
}
export function itemSubtotals(itemVectors: number[][], prices: number[], n: number): number[] {
  return __enforce("itemSubtotals", [itemVectors, prices, n], checks_itemSubtotals(itemVectors, prices, n), () => __core.itemSubtotals(itemVectors, prices, n));
}
function checks_bill(itemVectors: number[][], prices: number[], tax: number, tip: number, n: number, G: number): __Check[] {
  const __w2 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((itemVectors[i].length === n))))) return i; } return -1; })();
  const __w3 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((__core.sumTo(itemVectors[i], n) === prices[i]))))) return i; } return -1; })();
  const __w4 = ((): number => { for (let i = 0; i < itemVectors.length; i++) { if (!((!(((0 <= i) && (i < itemVectors.length))) || ((() => { for (let k = 0; k < n; k++) { if (!((!(((0 <= k) && (k < n))) || ((itemVectors[i][k] >= 0))))) return false; } return true; })())))) return i; } return -1; })();
  return [
    __C("bill#0", "n >= 1", ((n >= 1)), () => ({ "n": n })),
    __C("bill#1", "itemVectors.length === prices.length", ((itemVectors.length === prices.length)), () => ({ "itemVectors.length": itemVectors.length, "prices.length": prices.length })),
    __C("bill#2", "forall(i, 0 <= i && i < itemVectors.length ==> itemVectors[i].length === n)", __w2 === -1, () => ({ "i": __w2 })),
    __C("bill#3", "forall(i, 0 <= i && i < itemVectors.length ==> sumTo(itemVectors[i], n) === prices[i])", __w3 === -1, () => ({ "i": __w3 })),
    __C("bill#4", "forall(i, 0 <= i && i < itemVectors.length ==> forall(k, 0 <= k && k < n ==> itemVectors[i][k] >= 0))", __w4 === -1, () => ({ "i": __w4 })),
    __C("bill#5", "sumTo(prices, prices.length) >= 1", ((__core.sumTo(prices, prices.length) >= 1)), () => ({ "sumTo(prices, prices.length)": __core.sumTo(prices, prices.length) })),
    __C("bill#6", "tax >= 0", ((tax >= 0)), () => ({ "tax": tax })),
    __C("bill#7", "tip >= 0", ((tip >= 0)), () => ({ "tip": tip })),
    __C("bill#8", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function bill(itemVectors: number[][], prices: number[], tax: number, tip: number, n: number, G: number): number[] {
  return __enforce("bill", [itemVectors, prices, tax, tip, n, G], checks_bill(itemVectors, prices, tax, tip, n, G), () => __core.bill(itemVectors, prices, tax, tip, n, G));
}
function checks_balances(paid: number[], owed: number[]): __Check[] {
  return [
    __C("balances#0", "paid.length === owed.length", ((paid.length === owed.length)), () => ({ "paid.length": paid.length, "owed.length": owed.length })),
    __C("balances#1", "sumTo(paid, paid.length) === sumTo(owed, owed.length)", ((__core.sumTo(paid, paid.length) === __core.sumTo(owed, owed.length))), () => ({ "sumTo(paid, paid.length)": __core.sumTo(paid, paid.length), "sumTo(owed, owed.length)": __core.sumTo(owed, owed.length) })),
  ];
}
export function balances(paid: number[], owed: number[]): number[] {
  return __enforce("balances", [paid, owed], checks_balances(paid, owed), () => __core.balances(paid, owed));
}
function checks_settle(balances: number[]): __Check[] {
  return [
    __C("settle#0", "balances.length >= 1", ((balances.length >= 1)), () => ({ "balances.length": balances.length })),
    __C("settle#1", "sumTo(balances, balances.length) === 0", ((__core.sumTo(balances, balances.length) === 0)), () => ({ "sumTo(balances, balances.length)": __core.sumTo(balances, balances.length) })),
  ];
}
export function settle(balances: number[]): number[] {
  return __enforce("settle", [balances], checks_settle(balances), () => __core.settle(balances));
}
function checks_roundToG(x: number, G: number): __Check[] {
  return [
    __C("roundToG#0", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function roundToG(x: number, G: number): number {
  return __enforce("roundToG", [x, G], checks_roundToG(x, G), () => __core.roundToG(x, G));
}
function checks_settleRounded(balances: number[], hub: number, G: number): __Check[] {
  return [
    __C("settleRounded#0", "balances.length >= 1", ((balances.length >= 1)), () => ({ "balances.length": balances.length })),
    __C("settleRounded#1", "0 <= hub && hub < balances.length", (((0 <= hub) && (hub < balances.length))), () => ({ "hub": hub, "balances.length": balances.length })),
    __C("settleRounded#2", "G >= 1", ((G >= 1)), () => ({ "G": G })),
  ];
}
export function settleRounded(balances: number[], hub: number, G: number): number[] {
  return __enforce("settleRounded", [balances, hub, G], checks_settleRounded(balances, hub, G), () => __core.settleRounded(balances, hub, G));
}
function checks_applyOp(bal: number[], from: number, to: number, amount: number): __Check[] {
  return [
    __C("applyOp#0", "0 <= from && from < bal.length", (((0 <= from) && (from < bal.length))), () => ({ "from": from, "bal.length": bal.length })),
    __C("applyOp#1", "0 <= to && to < bal.length", (((0 <= to) && (to < bal.length))), () => ({ "to": to, "bal.length": bal.length })),
  ];
}
export function applyOp(bal: number[], from: number, to: number, amount: number): number[] {
  return __enforce("applyOp", [bal, from, to, amount], checks_applyOp(bal, from, to, amount), () => __core.applyOp(bal, from, to, amount));
}
function checks_replay(froms: number[], tos: number[], amounts: number[], n: number): __Check[] {
  const __w3 = ((): number => { for (let k = 0; k < froms.length; k++) { if (!((!(((0 <= k) && (k < froms.length))) || (((0 <= froms[k]) && (froms[k] < n)))))) return k; } return -1; })();
  const __w4 = ((): number => { for (let k = 0; k < tos.length; k++) { if (!((!(((0 <= k) && (k < tos.length))) || (((0 <= tos[k]) && (tos[k] < n)))))) return k; } return -1; })();
  return [
    __C("replay#0", "n >= 1", ((n >= 1)), () => ({ "n": n })),
    __C("replay#1", "froms.length === tos.length", ((froms.length === tos.length)), () => ({ "froms.length": froms.length, "tos.length": tos.length })),
    __C("replay#2", "tos.length === amounts.length", ((tos.length === amounts.length)), () => ({ "tos.length": tos.length, "amounts.length": amounts.length })),
    __C("replay#3", "forall(k, 0 <= k && k < froms.length ==> 0 <= froms[k] && froms[k] < n)", __w3 === -1, () => ({ "k": __w3 })),
    __C("replay#4", "forall(k, 0 <= k && k < tos.length ==> 0 <= tos[k] && tos[k] < n)", __w4 === -1, () => ({ "k": __w4 })),
  ];
}
export function replay(froms: number[], tos: number[], amounts: number[], n: number): number[] {
  return __enforce("replay", [froms, tos, amounts, n], checks_replay(froms, tos, amounts, n), () => __core.replay(froms, tos, amounts, n));
}

export const can = {
  sumTo: (arr: number[], n: number): boolean => __holds(checks_sumTo(arr, n)),
  allocate: (total: number, weights: number[], G: number): boolean => __holds(checks_allocate(total, weights, G)),
  billTotals: (subtotals: number[], tax: number, tip: number, G: number): boolean => __holds(checks_billTotals(subtotals, tax, tip, G)),
  itemShare: (price: number, claimers: number[], claimerWeights: number[], n: number, G: number): boolean => __holds(checks_itemShare(price, claimers, claimerWeights, n, G)),
  vectorAdd: (a: number[], b: number[]): boolean => __holds(checks_vectorAdd(a, b)),
  itemSubtotals: (itemVectors: number[][], prices: number[], n: number): boolean => __holds(checks_itemSubtotals(itemVectors, prices, n)),
  bill: (itemVectors: number[][], prices: number[], tax: number, tip: number, n: number, G: number): boolean => __holds(checks_bill(itemVectors, prices, tax, tip, n, G)),
  balances: (paid: number[], owed: number[]): boolean => __holds(checks_balances(paid, owed)),
  settle: (balances: number[]): boolean => __holds(checks_settle(balances)),
  roundToG: (x: number, G: number): boolean => __holds(checks_roundToG(x, G)),
  settleRounded: (balances: number[], hub: number, G: number): boolean => __holds(checks_settleRounded(balances, hub, G)),
  applyOp: (bal: number[], from: number, to: number, amount: number): boolean => __holds(checks_applyOp(bal, from, to, amount)),
  replay: (froms: number[], tos: number[], amounts: number[], n: number): boolean => __holds(checks_replay(froms, tos, amounts, n)),
};
